[펭귄] Test pull request
boostcamp-ai-tech-4/ai-tech-interview pull request #11
Opened 2021-04-13 13:07 UTC by CoodingPenguin

- 부먹 vs 찍먹
- 부먹이면 승인, 찍먹이면 거절

2021-04-13 13:09 UTC, bsm8734 submitted a review, later dismissed
부먹

2021-04-13 13:10 UTC, changwoomon commented
🥕

2021-04-13 13:10 UTC, Heeseok-Jeong commented
Where are approve and reject buttons? TT

2021-04-13 13:12 UTC, changwoomon requested changes
aaa

2021-04-13 13:16 UTC, Heeseok-Jeong requested changes
찍먹

2021-04-13 13:17 UTC, Heeseok-Jeong approved these changes

2021-04-13 13:18 UTC, changwoomon approved these changes
저는 "부먹파"입니다.

2021-04-13 13:18 UTC, bsm8734 approved these changes

2021-04-13 13:19 UTC, merged

2022-08-08 13:33 UTC, CoodingPenguin commented
github discord webhook 테스트

2022-08-08 13:34 UTC, CoodingPenguin commented
discord webhook test

2022-08-08 13:35 UTC, CoodingPenguin commented
discord webhook test