[히스] Update contents
boostcamp-ai-tech-4/ai-tech-interview pull request #26
Opened 2021-04-18 15:09 UTC by Heeseok-Jeong

2021-04-18 15:21 UTC, CoodingPenguin commented on answers/statistics-math.md
> +![고유값 공식](https://github.com/boostcamp-ai-tech-4/ai-tech-interview/blob/main/images/heath/eigen-formula.jpeg)
ㅇ

2021-04-18 15:24 UTC, CoodingPenguin requested changes
이미지 경로와 References 양식 변경 부탁드립니다!

2021-04-18 15:24 UTC, CoodingPenguin commented on answers/statistics-math.md
> +![고유값 공식](https://github.com/boostcamp-ai-tech-4/ai-tech-interview/blob/main/images/heath/eigen-formula.jpeg)
절대경로 말고 상대경로로 쓰셔야 이미지가 뜰 것 같습니다! 현재 보여지는 페이지는 이미지가 뜨지 않습니다.
`![고유값 공식](../images/heath/eigen-formula.jpeg)`로 변경 부탁드립니다!

2021-04-18 15:24 UTC, CoodingPenguin commented on answers/statistics-math.md
> +- [통계학 맛보기](https://velog.io/@dldydldy75/%EB%B2%A0%EC%9D%B4%EC%A6%88-%ED%86%B5%EA%B3%84%ED%95%99-%EB%A7%9B%EB%B3%B4%EA%B8%B0)
`[블로그 포스트 제목 - 블로그이름]` or `[블로그 포스트 제목 - 블로그 저자]`로 수정 부탁드립니다!

2021-04-18 16:50 UTC, Heeseok-Jeong commented on answers/statistics-math.md
> +![고유값 공식](https://github.com/boostcamp-ai-tech-4/ai-tech-interview/blob/main/images/heath/eigen-formula.jpeg)
이거 제가 그냥 이미지 파일 이름 잘못적은거였어요 ..허헣헣ㅎ

2021-04-18 16:56 UTC, Heeseok-Jeong commented on answers/statistics-math.md
> +- [통계학 맛보기](https://velog.io/@dldydldy75/%EB%B2%A0%EC%9D%B4%EC%A6%88-%ED%86%B5%EA%B3%84%ED%95%99-%EB%A7%9B%EB%B3%B4%EA%B8%B0)
수정 했습니다!

2021-04-18 17:10 UTC, bsm8734 approved these changes

2021-04-18 17:12 UTC, CoodingPenguin commented on answers/statistics-math.md
> +![고유값 공식](https://github.com/boostcamp-ai-tech-4/ai-tech-interview/blob/main/images/heath/eigen-formula.jpeg)
그렇네용! 수정 감사합니다!

2021-04-18 17:13 UTC, CoodingPenguin approved these changes
수고하셨습니다👍

2021-04-19 05:23 UTC, changwoomon approved these changes
고생하셨습니다!

2021-04-19 05:26 UTC, merged